name: CI

on:
  push:
    branches:
      - '*'
    paths-ignore:
      - '.idea/**'
      - '.gitattributes'
      - '.github/**.json'
      - '.gitignore'
      - '.gitmodules'
      - '**.md'
      - 'LICENSE'
      - 'NOTICE'
  pull_request:
    branches:
      - '*'  
    paths-ignore:
      - '.idea/**'
      - '.gitattributes'
      - '.github/**.json'
      - '.gitignore'
      - '.gitmodules'
      - '**.md'
      - 'LICENSE'
      - 'NOTICE'
  workflow_dispatch:
  workflow_call:

jobs:
  build-apk:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: 21
      - uses: gradle/actions/setup-gradle@v3
        with:
          cache-encryption-key: Da25KUVSE5jbGds2zXmfXw==
          gradle-home-cache-cleanup: true
      - name: Write sign info
        if: github.repository_owner == 'ELY3M'
        run: |
          if [ ! -z "${{ secrets.KEY }}" ]; then
            echo storePassword='${{ secrets.PASSWORD }}' >> keystore.properties
            echo keyAlias='${{ secrets.ALIAS }}' >> keystore.properties
            echo keyPassword='${{ secrets.PASSWORD }}' >> keystore.properties
            echo storeFile='${{ github.workspace }}/key.jks' >> keystore.properties
            echo ${{ secrets.KEY }} | base64 --decode > ${{ github.workspace }}/key.jks
          fi
          
      - name: Build APK
        run: ./gradlew assembleLawnWithQuickstepMarketRelease
        
      - name: current dir
        run: | 
            ls -la build/outputs/apk/lawnWithQuickstepMarket      
        
      - name: Upload artifact
        uses: actions/upload-artifact@v4            
        id: upload
        with:
          name: APK
          path: build/outputs/apk/**/*.apk
        
      - name: Output artifact ID
        run:  echo 'Artifact ID is ${{ steps.upload.outputs.artifact-id }}'        
          
      - name: Output Artifact URL
        run:  echo 'Artifact URL is ${{ steps.upload.outputs.artifact-url }}'
        
