name: CI

on:
  push:
    branches:
      - '*'
    paths-ignore:
      - '.idea/**'
      - '.gitattributes'
      - '.github/**.json'
      - '.gitignore'
      - '.gitmodules'
      - '**.md'
      - 'LICENSE'
      - 'NOTICE'
  pull_request:
    branches:
      - '*'  
    paths-ignore:
      - '.idea/**'
      - '.gitattributes'
      - '.github/**.json'
      - '.gitignore'
      - '.gitmodules'
      - '**.md'
      - 'LICENSE'
      - 'NOTICE'
  workflow_dispatch:
  workflow_call:

jobs:
  build-apk:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: 21
      - uses: gradle/actions/setup-gradle@v3
        with:
          cache-encryption-key: Da25KUVSE5jbGds2zXmfXw==
          gradle-home-cache-cleanup: true
          
      - name: Build APK
        run: ./gradlew assembleLawnWithQuickstepMarketRelease
        
      - name: current dir
        run: | 
            ls -la build/outputs/apk/lawnWithQuickstepMarket/release    

      - name: Sign APK
        uses: r0adkll/sign-android-release@v1
        id: sign_app
        with:
          releaseDirectory: build/outputs/apk/lawnWithQuickstepMarket/release/
          signingKeyBase64: ${{ secrets.KEY }}
          alias: ${{ secrets.ALIAS }}
          keyStorePassword: ${{ secrets.PASSWORD }}
          keyPassword: ${{ secrets.PASSWORD }}

      - name: Output Signed APK
        run:  echo 'Signed APK is ${{ steps.sign_app.outputs.signedReleaseFile }}' 
        
      - name: Upload artifact
        uses: actions/upload-artifact@v4            
        id: upload
        with:
          name: release-apk
          path: build/outputs/apk/**/*.apk
        
      - name: Output artifact ID
        run:  echo 'Artifact ID is ${{ steps.upload.outputs.artifact-id }}'        
          
      - name: Output Artifact URL
        run:  echo 'Artifact URL is ${{ steps.upload.outputs.artifact-url }}'
        
  publish-github-release:
    runs-on: ubuntu-latest
    needs: build-apk
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: Release APK
          path: build/outputs/apk/lawnWithQuickstepMarket/release  
      - name: Publish GitHub release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.run_number }}
          prerelease: false
          draft: false
          body: ${{ github.event.head_commit.message }}
          files: build/outputs/apk/lawnWithQuickstepMarket/release/*.apk
          name: ${{ github.run_number }} 

          
        
        
        
        
       