name: Release update

on:
  workflow_dispatch:
    inputs:
      artifactName:
        description: Artifact name
        type: string
        required: true
      tagName:
        description: Tag name
        type: string
        required: true
      prerelease:
        description: Prerelease
        type: boolean
        required: true
      releaseName:
        description: Release name
        type: string
        required: true

jobs:
  build-release-apk:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: 21
      - uses: gradle/actions/setup-gradle@v3
        with:
          gradle-home-cache-cleanup: true
      - name: Build release APK
        run: ./gradlew assembleLawnWithQuickstepMarketRelease
      - name: Write sign info
        if: github.repository_owner == 'ELY3M'
        run: |
          if [ ! -z "${{ secrets.KEY }}" ]; then
            echo storePassword='${{ secrets.PASSWORD }}' >> keystore.properties
            echo keyAlias='${{ secrets.ALIAS }}' >> keystore.properties
            echo keyPassword='${{ secrets.PASSWORD }}' >> keystore.properties
            echo storeFile='${{ github.workspace }}/key.jks' >> keystore.properties
            echo ${{ secrets.KEY }} | base64 --decode > ${{ github.workspace }}/key.jks
          fi
      - name: Rename artifact
        continue-on-error: true
        run: mv "${{ steps.build-release-apk.outputs.signedReleaseFile }}" "${{ github.event.inputs.artifactName }}"
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: Release APK
          path: ${{ github.event.inputs.artifactName }}

  publish-github-release:
    runs-on: ubuntu-latest
    needs: build-release-apk
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: Release APK
          path: artifacts/release-apk
      - name: Publish GitHub release
        uses: softprops/action-gh-release@v2
        with:
          draft: false
          prerelease: false    
          tag_name: ${{ github.run_number }}
          body: ${{ github.event.head_commit.message }}
          files: artifacts/release-apk/${{ github.event.inputs.artifactName }}
          name: ${{ github.event.inputs.releaseName }}


